### PR TITLE
Transpile build to ES5

### LINKED ISSUE #37: Transpile to ES5
I want to use this package but it contains non-es5 keywords (`const`) in the output file.

### PR DESCRIPTION
**Pull request by f1cognite**
Fixes #37

### CODE REVIEW

**Comment by f1cognite** [comment]
This project is not targeting `es5`? The output build (`build/src/index.js`) has keywords like `const` which is `es2015`. So I can't use this package if I want to target `es5` without transpiling the package.
This PR will replace `const` (es2015) with `var` (es5).

**Comment by JustinBeckwith** [comment]
I stand corrected! You're right, we're using `es2016` by default today.  I'm a little worried about the performance implications of down-compiling that low.  From what I can tell, `const` and `let` are supported in any reasonably modern browser:
https://caniuse.com/#search=const

Is there a specific browser version you need to try and support?

**Comment by Nickman87** [comment]
There are arrow functions that remain in the build, those don't work on IE11 (issue I'm running into)

**Comment by JustinBeckwith** [comment]
Apologies - there's no way I can try to support IE with this one.

**Pull request closed without merging**
