### PR TITLE
fix: reject error when a method called inside the axios interceptor throws error

### LINKED ISSUE #32: Error when a method called inside the axios interceptor throws a custom error
Error `cannot read property 'raxConfig' of undefined` is occurring when a method called inside the axios interceptor throws a custom error.

**Example:**
**Interceptor:**
```
axios.interceptors.request.use (
	async request => {
		request.headers.Authorization = await auth.getToken();
		return request
	},
	error => { ... }
);
```
**Method (`auth.getToken()`):**
```
	async getToken() {
		if (!this.auth.getCachedSession().isValid()) {
			throw new Error('Session has expired.');
		} else {
			return this.getAccessToken();
		}
	}
```
This error is happenning because custom error does not have a `config` object. Then the `onError` method of the `retry-axios` try to access `error.config,raxConfig` 

**A possible fix would be modifying `onError` function as following.**
```
function onError(err) {
	if (!err.config) {
		return Promise.reject(err);
	}
        ...
}
```

### PR DESCRIPTION
**Pull request by ShanikaEdiriweera**
Fix error when a method called inside the axios interceptor throws a custom error

Fix #32

### CODE REVIEW

**Comment by ShanikaEdiriweera** [comment]
@JustinBeckwith Why does this circle ci test fail
subject may not be empty [subject-empty]
type may not be empty [type-empty]
I have no idea how to pass this test. Please guide me.

**Comment by opyate** [comment]
@ShanikaEdiriweera see https://github.com/conventional-changelog/commitlint

**Comment by ShanikaEdiriweera** [comment]
@JustinBeckwith Sorry. I won't be able to work on it. I am a bit busy these days.

**Comment by JustinBeckwith** [comment]
Totally understand.  Thanks!

**Pull request closed without merging**
