### PR TITLE
fixes #1

### LINKED ISSUE #1: Exception in function shouldRetryRequest() when checking HTTP methods to retry
In function `shouldRetryRequest` there's this block of code
```
    // Only retry with configured HttpMethods.
    if (!err.config.method ||
        config.httpMethodsToRetry.indexOf(err.config.method.toUpperCase()) < 0) {
        return false;
    }
```
that fails evaluating second condition, because `httpMethodsToRetry` is an object, not an array.

Below goes the output from dev console, when the breakpoint was set on the line given above ^^^:
```
config.httpMethodsToRetry
{0: "GET", 1: "HEAD", 2: "OPTIONS", 3: "DELETE", 4: "PUT"}
```

That looks different from what gets set in `raxConfig`
```
    const raxConfig = {
    ....
        
      // HTTP methods to automatically retry.  Defaults to:
      // ['GET', 'HEAD', 'OPTIONS', 'DELETE', 'PUT']
      httpMethodsToRetry: ['GET', 'HEAD', 'OPTIONS', 'DELETE', 'PUT'],
    }
```

### PR DESCRIPTION
**Pull request by opyate**

### CODE REVIEW

**Comment by opyate** [comment]
node6 is failing because I'm using `Object.values`.
How does everyone suggest I fix? Shim?

**Comment by gpetrioli** [comment]
> 
> 
> node6 is failing because I'm using `Object.values`.
> How does everyone suggest I fix? Shim?

I would go with a shim but not sure how @JustinBeckwith feels about adding dependencies.

**Comment by opyate** [comment]
@gpetrioli OK, I've just added a `values` to be called instead of `Object.values` for now:
```
// tslint:disable-next-line no-any
const values = (objOrArray: {[key: string]: any}) => {
  return Object.keys(objOrArray).map((key: string) => objOrArray[key]);
};
```

I'll leave it up to @JustinBeckwith to add a shim/polyfill/etc if he feels OK with extra dependencies.

(...and I've also added the fix for the `httpMethodsToRetry` ;) )

**Comment by JustinBeckwith** [comment]
Just to make sure I'm not entirely nuts - what version of axios are y'all using where you see this problem?

**Comment by gpetrioli** [comment]
This problem is definitely present in **0.18.0** version of axios. 

(*with axios@next there is a different set of problems*)

**Comment by JustinBeckwith** [comment]
Sorry for all the trouble here folks.  Super weird bug in axios.  This is addressed in #83 in a slightly different way, so closing this out.

**Pull request closed without merging**
