### PR TITLE
fix: transpile to es5

### PR DESCRIPTION
**Pull request by iamChristian**
When using the suggested [babel-loader config](https://github.com/babel/babel-loader#usage) in Webpack (exclude `node_modules`) retry-axios causes parsing error in IE due to arrow functions.

Updating the TypeScript target to ES5 enables compatibility without further configuration of Webpack.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Greetings!  I'm a little scared to accept this one tbh.   We're not super crisp on what versions of the browser the module supports, and don't have web tests specifically in place (that I remember at least ...)

Before accepting anything to better support IE - I'd like to have:
- A policy on what versions of the browser we want to support
- Tests in place that verify the supported versions

Any interest in working together on this?

**Comment by iamChristian** [comment]
Cheers Justin, to be honest since raising the PR I've seen an increasing pattern of libraries requiring transpilation. Maybe a note making this clear in the README would suffice?

**Comment by AndyOGo** [comment]
Hey,

I just raised an issue regarding IE11 #106.
It would be great if this could be made clear, wheter transpilation is required or it will be fixed here.

Kind regards,
Andreas

**Comment by JustinBeckwith** [comment]
At this stage, I don't think es5 or Internet Explorer are things we're going to try supporting :(

**Pull request closed without merging**
